### ISSUE TITLE
Create Reusable UI Components

### ISSUE THREAD

**Issue by oksachi** [CMPUT301W22T07/COLLECTQR#40]
###### Daryna
- [x] All 5 History Screens
- [x] 4 Leaderboard Screens
- [x] Scrim
- [x] An App Bar1

###### Patrick
- [x] Leaderboard Screens
- [x] Leaderboard List Items
- [x] Export QR Code and Share QR Code Activities
- [ ] Floating Action Buttons & their icons

###### Sachith
- [x] Leaderboard Floating Profile Card
- [x] Bottom Navigation and all Segment Variants
- [x] 3/4 App Bars & rofile Dialog Box
- [x] 5 Login Screens

###### To-Do
- [ ] Make Share Sheet a Seperate Component
- [ ] Modify History and Leaderboard for Admin (Delete functions)
- [ ] QR Code Scan / Object Capture Buttons
- [ ] Switch components
- [ ] Assign Project colours to all components for dynamic colouring
